name: Test

on: [push]

permissions: {}

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    container:
      image: archlinux:base-devel # zizmor: ignore[unpinned-images]
      options: --user root

    steps:
      - name: Update packages
        run: pacman -Syu --noconfirm

      - name: Install dependencies
        run: pacman -S --needed --noconfirm base-devel git extra-cmake-modules qt6-tools yaml-cpp gtest

      - name: Check out repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
          submodules: 'recursive'

      - name: Configure CMake
        run: cmake -B "${GITHUB_WORKSPACE}/build" -DBUILD_TESTS=ON

      - name: Build
        run: cmake --build "${GITHUB_WORKSPACE}/build" -j$(nproc)

      - name: Run tests
        run: ctest --test-dir "${GITHUB_WORKSPACE}/build" --output-on-failure --verbose

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
